### ISSUE TITLE
Hits included in tracks that shouldn't be there

### ISSUE THREAD

**Issue by LiamOS** [DUNE/dune-tms#120]
In file`/pnfs/dune/persistent/users/kleykamp/nd_production/2024-05-13_lar_only_rhc/edep/RHC/00m/00/antineutrino.0_1715654453.edep.root` for spill 10, the reconstructed track is as shown:
![spill_010](https://github.com/DUNE/dune-tms/assets/2707138/2aa9d824-3232-4472-a8f3-d88b3864d02b)
This happens in a number of other events in other files, and also happens in the NERSC sample files.

**Comment by AsaNehm** [comment]
Starting to work on this

**Comment by AsaNehm** [comment]
It seems that there is an effect that 'randomly' assigns the x position of a hit to 0 at the end. This is an effect and not real as this neither appears in the truth hits nor in the hits for reconstruction before the reco starts. After the 3D matching this effect is there. I'll trace this through and fix it

**Comment by AsaNehm** [comment]
I think I managed to solve the issue. See branch 120-...

**Comment by AsaNehm** [comment]
Forgot to fix the 'random' hits in the middle of tracks. Now taken care of by handling two hits per plane in the matching step correctly

**Comment by AsaNehm** [comment]
Will be merged into the main branch with PR 122
