### ISSUE TITLE
SpillNo is not linear

### ISSUE THREAD

**Issue by jdkio** [DUNE/dune-tms#164]
Here I'm output entry_numer: SpillNo, SliceNo, EntryNo
```
34: 59, 4, 90
35: 59, 5, 91
36: 59, 6, 92
37: 59, 7, 93
38: 76, 0, 86
39: 76, 1, 111
```
SpillNo goes from 59 to 76 which is not right

**Comment by AsaNehm** [comment]
Has this been solved with the merged PR 165?

**Comment by jdkio** [comment]
Yes, closing now
